// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppGenerateV2(arg1, arg2) {
  return window['go']['main']['App']['AppGenerateV2'](arg1, arg2);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function GetPlist() {
  return window['go']['main']['App']['GetPlist']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RefetchAccountPage() {
  return window['go']['main']['App']['RefetchAccountPage']();
}

export function RegeneratePassword(arg1) {
  return window['go']['main']['App']['RegeneratePassword'](arg1);
}

export function UpdateUsername(arg1, arg2) {
  return window['go']['main']['App']['UpdateUsername'](arg1, arg2);
}
