// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utilities} from '../models';

export function AppGenerateV2(arg1:string,arg2:utilities.GenerateOptions):Promise<string>;

export function Connect(arg1:string,arg2:string):Promise<string>;

export function DeletePassword(arg1:string):Promise<string>;

export function GetData():Promise<string>;

export function GetPlist():Promise<string>;

export function Logout():Promise<string>;

export function RefetchAccountPage():Promise<string>;

export function RegeneratePassword(arg1:string):Promise<string>;

export function UpdateUsername(arg1:string,arg2:string):Promise<string>;
